# Site settings
title: Testing Rotation Controllers Documentation
url: "http://3dui.github.io/testing-rotation-controllers/" # the base hostname & protocol for your site
# Build settings
markdown: kramdown
encoding: UTF-8
